# Generated by Django 4.0.3 on 2022-04-07 10:32

from django.db import migrations, models
import fishries.models


class Migration(migrations.Migration):

    dependencies = [
        ('fishries', '0002_token_book_token_number_delete_admin_token_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffProxyModel',
            fields=[
            ],
            options={
                'verbose_name': 'Staff',
                'verbose_name_plural': 'Staffs',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('fishries.user',),
            managers=[
                ('objects', fishries.models.StaffManager()),
            ],
        ),
        migrations.AlterField(
            model_name='token_book',
            name='approved',
            field=models.PositiveIntegerField(choices=[('1', 'Approved'), ('0', 'Rejected')], default=False, verbose_name='approved'),
        ),
    ]
