# Generated by Django 4.0.3 on 2022-04-08 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fishries', '0003_staffproxymodel_alter_token_book_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token_book',
            name='approved',
            field=models.PositiveIntegerField(choices=[(0, 'Rejected'), (1, 'Approved'), (2, 'Pending')], default=2, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='token_book',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Owner1', to='fishries.boat_details'),
        ),
        migrations.AlterField(
            model_name='token_book',
            name='token_number',
            field=models.CharField(max_length=25, null=True, unique=True),
        ),
    ]
