# Generated by Django 4.0.3 on 2022-04-08 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fishries', '0004_alter_token_book_approved_alter_token_book_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crew',
            name='boat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fishries.boat_details'),
            preserve_default=False,
        ),
    ]
