# Generated by Django 4.0.3 on 2022-04-08 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishries', '0005_crew_boat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token_book',
            name='token_number',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
