# Generated by Django 4.0.3 on 2022-04-08 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishries', '0006_alter_token_book_token_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token_book',
            name='number_of_crew',
            field=models.IntegerField(),
        ),
    ]
